import Head from 'next/head'
import { GetServerSidePropsContext } from 'next'

import { Box, Button, Container } from '@chakra-ui/react'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { HomeHeroCategories } from '@/components/HomeHeroCategories'

import { Category } from '@/interfaces/Categories'

type Product = {
  id: number;
  title: string;
  price: string;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  }
}

type HomeProps = {
  products: Product[];
  categories: Category[];
}

export default function Home({ products, categories }: HomeProps) {
  return (
    <>
      <Head>
        <title>Ecommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopBar />

        <Box marginBottom='2rem'>
          <Header />
        </Box>

        <Container size='lg'>
          <HomeHeroCategories categories={categories} />
        </Container>
      </main>
    </>
  )
}

export async function getServerSideProps(contex: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())

  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res=>res.json())

  console.log(categories)

  return {
    props: {
      products,
      categories
    }
  }
}