import Head from 'next/head'
import { Grid, GridItem, Heading } from '@chakra-ui/react'
import { Button } from '@chakra-ui/react'
import { Header } from '@/components/Header'
import { GetServerSidePropsContext } from 'next'
import { slugify } from '@/utils/slugify'
import Image from 'next/image'
import { TopBar } from '@/components/TopBar'

type Product = {
  id: number;
  title: string;
  price: string;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  }
}

type Category = "electronics" | "jewelery" | "men's clothing" | "women's clothing";

type Props = {
  products: Product[];
  categories: Category[];
}

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>Ecommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopBar />

        <Header />

        <Grid
          gap='1rem'
          templateRows='200px 260px'
          templateColumns='540px 255px 255px'
        >
          {categories.map((cat, id) => {
            const slug = slugify(cat)
            const imageUrl = `/pic-category-${slug}.jpg`

            if (id === 0) {
              return (
                <GridItem
                  key={id}
                  w='100%'
                  h='100%'
                  bg='blue.300'
                  position='relative'
                  rowSpan={2}
                >
                  <Image src={imageUrl} alt='' fill={true} />
                </GridItem>
              )
            }

            if (id === categories.length - 1) {
              return (
                <GridItem
                  key={id}
                  w='100%'
                  h='100%'
                  bg='blue.300'
                  position='relative'
                  colSpan={2}
                >
                  <Image src={imageUrl} alt='' fill={true} />
                </GridItem>
              )
            }

            return (
              <GridItem
                key={id}
                w='100%'
                h='100%'
                bg='blue.300'
                position='relative'
              >
                <Image src={imageUrl} alt='' fill={true} />
              </GridItem>
            )
          })}
        </Grid>
       
        <Button>Hola</Button>

      </main>
    </>
  )
}

export async function getServerSideProps(contex: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())

  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res=>res.json())

  console.log(categories)

  return {
    props: {
      products,
      categories
    }
  }
}