import Head from 'next/head'
import Image from 'next/image'
import { GetServerSidePropsContext } from 'next'

import { AspectRatio, Box, Container, Flex, Text } from '@chakra-ui/react'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { HomeHeroCategories } from '@/components/HomeHeroCategories'

import { Category } from '@/interfaces/Categories'
import { AdvantegItem } from '@/components/AdvantegItem'
import { AdvantegSection } from '@/components/AdvantegSection'

type Product = {
  id: number;
  title: string;
  price: string;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  }
}

type HomeProps = {
  products: Product[];
  categories: Category[];
}

export default function Home({ products, categories }: HomeProps) {
  return (
    <>
      <Head>
        <title>Ecommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <Box marginBottom='2rem'>
        <Header />
      </Box>

      <main>
        <Container size='lg'>
          <HomeHeroCategories categories={categories} />

          <AdvantegSection />
        </Container>       

        <Box
          width='255px'
          margin='2rem 0'
          border='1px solid'
          borderColor='gray.200'
        >
          <AspectRatio
            ratio={1}
            maxWidth='100%'
            position='relative'
          >
            <Image
              fill
              alt=''
              style={{ objectFit: 'contain' }}
              src='https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg'
            />
          </AspectRatio>
          <Text>Fjallraven - Foldack No. 1 Backpack, Fits is Laptiop</Text>
          <Text>$ 30.000</Text>
        </Box>
      </main>
    </>
  )
}

export async function getServerSideProps(contex: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())

  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res=>res.json())

  return {
    props: {
      products,
      categories
    }
  }
}